package schemagen

// Binding a description to Go: a type for each named shape, and the schema that
// reads and writes it.
//
// This is the other direction from reading a struct, and it shares the
// rendering with it: the field declarations, accessors and combinator calls
// come out of the same functions, so a schema generated from a description and
// one generated from a struct are the same code. Two emitters would drift.

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"

	"github.com/mbauer83/effect-golang-schema/schema/structure"
)

// BindingsFileName is the file this generator owns in each package it writes.
const BindingsFileName = "bindings_generated.go"

// WriteBindings returns the source binding every named shape reachable from the
// given descriptions.
//
// Reachable, because a description refers to its parts by name and each part
// needs a Go type of its own. Discovery order is the order the descriptions
// declare them, so the output is stable.
func WriteBindings(packageName string, descriptions ...structure.Node) ([]byte, error) {
	reachable, err := reachableShapes(descriptions)
	if err != nil {
		return nil, err
	}
	if len(reachable) == 0 {
		return nil, fmt.Errorf("no named shape was described")
	}

	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by schemagen; DO NOT EDIT.\n")
	fmt.Fprintf(&out, "// Edit the description and rerun: go generate ./...\n\n")
	fmt.Fprintf(&out, "package %s\n\n", packageName)
	fmt.Fprintf(&out, "import %q\n", schemaPackage)

	for _, shape := range reachable {
		if err := writeBinding(&out, shape, reachable); err != nil {
			return nil, err
		}
	}

	source, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("the generated source does not parse: %w\n%s", err, out.String())
	}
	return source, nil
}

func writeBinding(out *bytes.Buffer, shape structure.Node, reachable []structure.Node) error {
	switch inner := shape.(type) {
	case structure.Object:
		return writeObjectBinding(out, inner, markersFor(inner.Name, reachable))
	case structure.Union:
		return writeUnionBinding(out, inner)
	default:
		return fmt.Errorf("a description binds an object or a union, not %T", shape)
	}
}

// writeObjectBinding writes the struct and its schema. The schema is rendered
// by the same function the struct-reading direction uses, so the two produce
// identical code.
func writeObjectBinding(out *bytes.Buffer, shape structure.Object, markers []string) error {
	binding, err := structTypeOf(shape)
	if err != nil {
		return err
	}

	writeDoc(out, shape.Name, shape.Description)
	fmt.Fprintf(out, "type %s struct {\n", shape.Name)
	for index, member := range shape.Fields {
		field := binding.fields[index]
		if member.Description != "" {
			fmt.Fprintf(out, "// %s\n", member.Description)
		}
		fmt.Fprintf(out, "%s %s `json:%s`\n", field.name, field.goType, strconv.Quote(jsonTag(field)))
	}
	fmt.Fprintf(out, "}\n")

	for _, marker := range markers {
		fmt.Fprintf(out, "\nfunc (%s) %s() {}\n", shape.Name, marker)
	}
	return renderType(out, binding, "its description")
}

func writeDoc(out *bytes.Buffer, name string, doc string) {
	fmt.Fprintf(out, "\n")
	if doc != "" {
		fmt.Fprintf(out, "// %s\n//\n", doc)
	}
	fmt.Fprintf(out, "// %s is generated from its description.\n", name)
}

func jsonTag(field structField) string {
	if field.optional {
		return field.wire + ",omitempty"
	}
	return field.wire
}

// structTypeOf turns a described object into the form the shared renderer
// takes.
func structTypeOf(shape structure.Object) (structType, error) {
	binding := structType{name: shape.Name, doc: shape.Description}
	for _, member := range shape.Fields {
		field, err := structFieldOf(shape.Name, member)
		if err != nil {
			return structType{}, err
		}
		binding.fields = append(binding.fields, field)
	}
	if len(binding.fields) == 0 {
		return binding, nil
	}
	return binding, nil
}

func structFieldOf(owner string, member structure.Field) (structField, error) {
	name, err := goFieldName(member.Name)
	if err != nil {
		return structField{}, fmt.Errorf("%s: %w", owner, err)
	}
	element, err := goTypeOf(member.Node)
	if err != nil {
		return structField{}, fmt.Errorf("%s.%s: %w", owner, member.Name, err)
	}
	shape, err := schemaExpression(member.Node)
	if err != nil {
		return structField{}, fmt.Errorf("%s.%s: %w", owner, member.Name, err)
	}

	field := structField{
		name:     name,
		wire:     member.Name,
		doc:      member.Description,
		shape:    shape,
		optional: member.Optional,
		goType:   element,
		element:  element,
	}
	if member.Optional {
		// An optional member is a pointer, so absence is the pointer being nil
		// rather than a zero value the schema would have to guess about.
		field.goType = "*" + element
	}
	return field, nil
}
