// Code generated by schemagen; DO NOT EDIT.
// Edit the description and rerun: go generate ./...

package inventory

import "github.com/mbauer83/effect-golang-schema/schema"

// one stocked line
//
// Item is generated from its description.
type Item struct {
	// the stock-keeping unit, three letters and five digits
	Sku string `json:"sku"`
	// how many are on hand
	OnHand uint16 `json:"onHand"`
	// what one unit weighs
	WeightGrams float32  `json:"weightGrams"`
	ID          string   `json:"id"`
	Tags        []string `json:"tags"`
	Note        *string  `json:"note,omitempty"`
}

// ItemSchema describes Item. It is generated from its description.
var ItemSchema = schema.Struct[Item]("Item",
	schema.FieldAt("sku", schema.Text().Check(schema.Pattern("^[A-Z]{3}-[0-9]{5}$")),
		func(value *Item) *string { return &value.Sku }).WithDescription("the stock-keeping unit, three letters and five digits"),
	schema.FieldAt("onHand", schema.Uint16(),
		func(value *Item) *uint16 { return &value.OnHand }).WithDescription("how many are on hand"),
	schema.FieldAt("weightGrams", schema.Float32(),
		func(value *Item) *float32 { return &value.WeightGrams }).WithDescription("what one unit weighs"),
	schema.FieldAt("id", schema.UUID(),
		func(value *Item) *string { return &value.ID }),
	schema.FieldAt("tags", schema.List(schema.Text()).Check(schema.MinItems[string](1)),
		func(value *Item) *[]string { return &value.Tags }),
	schema.OptionalFieldOf("note", schema.Text().Check(schema.MaxLength(200)),
		func(value Item) (string, bool) {
			var absent string
			if value.Note == nil {
				return absent, false
			}
			return *value.Note, true
		},
		func(value *Item, field string) { value.Note = &field }),
).WithDescription("one stocked line")

// a change in what is stocked
//
// Movement is generated from its description.
type Movement interface{ isMovement() }

// MovementSchema describes Movement. It is generated from its description.
var MovementSchema = schema.Union[Movement]("Movement",
	schema.VariantOf("received", ReceivedSchema,
		func(value Movement) (Received, bool) { variant, is := value.(Received); return variant, is },
		func(variant Received) Movement { return variant }).WithDescription("stock arriving"),
	schema.VariantOf("shipped", ShippedSchema,
		func(value Movement) (Shipped, bool) { variant, is := value.(Shipped); return variant, is },
		func(variant Shipped) Movement { return variant }).WithDescription("stock leaving"),
).WithDescription("a change in what is stocked")

// Received is generated from its description.
type Received struct {
	Count uint16 `json:"count"`
}

func (Received) isMovement() {}

// ReceivedSchema describes Received. It is generated from its description.
var ReceivedSchema = schema.Struct[Received]("Received",
	schema.FieldAt("count", schema.Uint16(),
		func(value *Received) *uint16 { return &value.Count }),
)

// Shipped is generated from its description.
type Shipped struct {
	Count uint16 `json:"count"`
	To    string `json:"to"`
}

func (Shipped) isMovement() {}

// ShippedSchema describes Shipped. It is generated from its description.
var ShippedSchema = schema.Struct[Shipped]("Shipped",
	schema.FieldAt("count", schema.Uint16(),
		func(value *Shipped) *uint16 { return &value.Count }),
	schema.FieldAt("to", schema.Hostname(),
		func(value *Shipped) *string { return &value.To }),
)
